name: Export Calls to Google Doc

on:
  schedule:
    - cron: '*/5 * * * *'  # Запуск каждые 5 минут
  workflow_dispatch:       # Ручной запуск

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout репозитория с правами
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 🐍 Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🚀 Запуск экспорта звонков
        run: python download_jessica_calls_final.py

      - name: 💾 Commit и push last_run.txt
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add last_run.txt
          git commit -m "update last_run after export" || echo "⏭ Нечего коммитить"
          git push origin HEAD:${{ github.ref }}
